**round() function**

In [1]:
round(1.1139,3)

1.114

**Print statement practice (sep,end)**

In [2]:
print("12345",True,"ali" ,sep='..')

12345..True..ali


In [3]:
print("12345",True,"ali" ,sep='\n')

12345
True
ali


In [4]:
print("12345",True,"ali" ,sep='\t')

12345	True	ali


In [5]:
print("12345",True,"ali")
print("arifin")

12345 True ali
arifin


In [6]:
print("12345",True,"ali",end="")
print("arifin")

12345 True aliarifin


In [9]:
print("12345",True,"ali",end="\n")
print("arifin")

12345 True ali
arifin


In [10]:
print("12345",True,"ali",end="\t")
print("arifin")

12345 True ali	arifin


**Math module**

In [11]:
import math
print(math.pi)

3.141592653589793


In [12]:
math.trunc(4.953999)

4

In [13]:
math.floor(5.8)

5

In [14]:
math.tan(45)

1.6197751905438615

In [15]:
math.sqrt(9)

3.0

In [16]:
math.radians(90)

1.5707963267948966

In [17]:
math.degrees(2*math.pi)

360.0

In [18]:
math.exp(2)

7.38905609893065

In [19]:
math.pow(3,4)

81.0

In [24]:
math.remainder(18,7)

-3.0

In [25]:
18%7

4

In [21]:
math.gcd(75,70)

5

**Basic numpy practice**

In [47]:
import numpy as np
lis=[1,2,3,4,5]
np_lis=np.array(lis)
print(np_lis)
a=np_lis > 4
print(a)

[1 2 3 4 5]
[False False False False  True]


In [49]:
x=np_lis[np_lis > 4]
print(x)

[5]


In [50]:
import numpy as np
a=np.array([9,8,7,6])
a+2

array([11, 10,  9,  8])

In [53]:
np.std([1,1.1,1.2,1.3])


np.float64(0.11180339887498948)

In [54]:
np.std([1,1,1,1])

np.float64(0.0)

In [55]:
np.var([1,2,3])

np.float64(0.6666666666666666)

In [56]:
np.std([1,2,3])

np.float64(0.816496580927726)

In [57]:
np.corrcoef([1,2,3],[1,2,3])

array([[1., 1.],
       [1., 1.]])

**math & numpy**

In [58]:
import math
import numpy as np
r=np.array([1,2,3])
a=math.pi * r **2
a

array([ 3.14159265, 12.56637061, 28.27433388])

**list of tuples -> list (using list comprehension)**

In [59]:
a=[(1,2),(3,4),(5,6)]
pro=[i[0]*i[1] for i in a]
print(pro)

[2, 12, 30]


**Nested for loop practice**

In [60]:
for i in [1,2,3]:      #  1   1   1   2    2    2    3     3    3
  for j in [1,2,3]:    #  1   2   3   1    2    3    1     2    3
    print(i+j)         #  2   3   4   3    4    5    4     5    6


2
3
4
3
4
5
4
5
6


In [61]:
for i in [1,2,3]:                 #  1 1 1 2 2 2 3 3 3
  for j in range(3):              #  0 1 2 0 1 2 0 1 2
    print(i+j)                    #  1 2 3 2 3 4 3 4 5

1
2
3
2
3
4
3
4
5


In [62]:
for i in range(2,5):            # 2  2  3 3 3 4 4 4 4 
  for j in range(i):            # 0  1  0 1 2 0 1 2 3
    print(i+j)

2
3
3
4
5
4
5
6
7


In [63]:
for i in range(2,5):                  # 2 2  3 3 3  4 4 4 4
  for j in range(1,i+1):              # 1 2  1 2 3  1 2 3 4
      print(i/j)


2.0
1.0
3.0
1.5
1.0
4.0
2.0
1.3333333333333333
1.0


In [64]:
a=range(2,12)
type(a)

range

In [65]:
a=range(2,12)
for i in a:
  print(i)

2
3
4
5
6
7
8
9
10
11


**Arbitrary Arguments, args:**
If you do not know how many arguments that will be passed into your function, add * before the parameter name in the function definition.

This way the function will receive a **tuple** of arguments, and can access the items accordingly

In [66]:
def arifin(*args):
  return type(args)
arifin(1,2,3,4,5,6)

tuple

**Arbitrary Keyword Arguments** 

If you do not know how many keyword arguments that will be passed into your function, add two asterisk: ** before the parameter name in the function definition.

This way the function will receive a **dictionary** of arguments, and can access the items accordingly



In [67]:
def ali(**kwargs):
  return type(kwargs)
ali(a='188',c='2',d='4')

dict

In [68]:
ali(a=1,c=2,d=4)

dict

**iterrows() practice**

In [69]:
import pandas as pd
dic={'a':['ali','arifin'],'b':[3,4]}
df=pd.DataFrame(dic)
df

a  b
0     ali  3
1  arifin  4

In [70]:
for i,j in df.iterrows():
  print(str(i)+":"+str(j['a']))

0:ali
1:arifin


In [71]:
for k in df:
  print(k)

a
b


**nested function**

In [72]:
def capword(a):
  return a.capitalize()
capword('aRiFiN')

'Arifin'

In [73]:
def capitalist(a):
  return [a[0].capitalize(),a[1].capitalize()]
capitalist(['aRiFiN','alyyy'])

['Arifin', 'Alyyy']

In [75]:
def caplist(l):                                       # 1
  def cword(m):                                       # 3
    return m.capitalize()                             # 4
  return [cword(l[0]),cword(l[1])]                    # 2
caplist(["ali","alyy"])

['Ali', 'Alyy']

**while loop practice**

In [76]:
i=0
while i<5:
  print(i)
  i=i+1
  

0
1
2
3
4


In [77]:
i=-4
while i<5:
  print(i)
  i=i+1


-4
-3
-2
-1
0
1
2
3
4


In [78]:
i=-4
while i<1:
  print(i)
  i=i+1

-4
-3
-2
-1
0


In [81]:
c=5
id(c)

2160207135088

In [83]:
a=[[1,2,3],[1,2,3]]
print(len(a))

2


In [84]:
a=[[1,2,3],[1,2,3],[1,1,1]]
print(len(a))

3


In [85]:
a=[[1,1,1],[2,22,2],[3,3,33],[11,1,1]]
print(len(a))

4


In [86]:
a=[[1,1],[1,1,1,1],[1,1,1,1,1,1,1,1]]
print(len(a))

3


In [89]:
4%7

4

In [90]:
4%7+6

10